### ISSUE TITLE
Compile error in SimpleShapeDetector

### ISSUE THREAD

**Issue by spsaul20** [sandym/swiftpp#3]
Hello,
Thanks for making this tool.
I have encountered the following error when trying to compile the SimpleShapeDetector example:
Command /bin/sh failed with exit code 139

I have compiled swiftpp and added it to the SimpleShapeDetector project.  The run script look like the follow:
echo "swiftpp"
$PROJECT_DIR/SimpleShapeDetector/swiftpp '-Dswift=__attribute__((annotate("swift")))' "$PROJECT_DIR/SimpleShapeDetector/cxx-Bridging-Header.h"

Any help would be greatly appreciated.

**Comment by sandym** [comment]
Wow, thanks for trying it!

I found this: "Unix systems return errono 128+signal when a signal received. 128 + 11 = 139 . Signal 11 is SIGSEV (i.e. segmentation violation)."

Looks like swiftpp is crashing, it is working for me now so I'm updating to the latest clang trunk trying...

**Comment by spsaul20** [comment]
Thanks!

While I was waiting on your answer, I tried to rebuild the swiftpp tool and got the following errors:
swiftpp/src/SwiftppASTConsumer.cpp:65:66: No member named 'getAsTagDecl' in 'clang::Type'
swiftpp/src/SwiftppASTConsumer.cpp:70:61: No member named 'getAsTagDecl' in 'clang::Type'
swiftpp/src/SwiftppASTConsumer.cpp:82:60: No member named 'getExtValue' in 'llvm::APSInt'

I really did not understand why, since I build the tool earlier in the day.  I was not able to figure out what was different.

Also, when I built set up setup_llvm.txt you may want to add svn co -r 217018 ...  I do not think the latests llvm truncks are 217018 and I think without the -r it gets the latest trunk.

All of this may or may not have to do with the original problem that asked about.  If they do not I can make them separate issues.  If they are easy to answer or something you see I have done wrong, please let me know.

And again, thank you so much for creating this tool.  I am very eager to try it and see if it can help me use some c++ in my swift applications.

**Comment by sandym** [comment]
OK, I just got the latest llvm/clang trunk, recompile everything and it all work as expected here.  Note that I updated the code for the latest swift version too, the one with Xcode 6.3-beta. I changed the README to reflect this.

For llvm, yes, I was tracking the latest trunk, I think I'll use llvm 3.6 when it's released in the coming weeks and stop using trunk, so that I can have a more stable build environment.

Also, I just fixed a crash in swiftpp that was caused by my unfinished implementation of enum support. enum support is still unfinished, but the crash should be fixed now.

Finally, your build problems are really strange as those members clearly exists in the clang source, so I don't know... clean and rebuild ?

**Comment by spsaul20** [comment]
Your changes have help me get a bit farther along.  I am still experiencing some issues though.

I am getting the following error when I try to build SimpleShapeDetector:
'vector' file not found.

This error is in Path2D.h at line 13 where it says #include <vector>

I was unable to build libc++, so I am not sure if that is the reason vector is not being found.

When going through the setup_llvm instructions, once I get to ./buildit, there is an error.
ld: unknown option: -soname

Apparently OSX does not recognize -soname; I think for OSX it may have to be changed to -dylib_install_name -Wl.

When I made the replacement then I got the following error:
ld: library not found for -lrt

It seems as though -lrt is not supported on OSX.  After googling, it was suggested to remove -lrt.

But then I got the following errors:
Undefined symbols for architecture x86_64:
  "___cxa_current_primary_exception", referenced from:
      std::nested_exception::nested_exception() in exception.o
      std::current_exception() in exception.o
      std::nested_exception::nested_exception() in exception.o
  "___cxa_decrement_exception_refcount", referenced from:
      std::exception_ptr::~exception_ptr() in exception.o
      std::exception_ptr::~exception_ptr() in exception.o
      std::exception_ptr::operator=(std::exception_ptr const&) in exception.o
      std::nested_exception::~nested_exception() in exception.o
      std::nested_exception::~nested_exception() in exception.o
      std::nested_exception::~nested_exception() in exception.o
      std::nested_exception::rethrow_nested() const in exception.o
      ...
  "___cxa_increment_exception_refcount", referenced from:
      std::exception_ptr::exception_ptr(std::exception_ptr const&) in exception.o
      std::exception_ptr::exception_ptr(std::exception_ptr const&) in exception.o
      std::exception_ptr::operator=(std::exception_ptr const&) in exception.o
      std::nested_exception::rethrow_nested() const in exception.o
  "___cxa_rethrow_primary_exception", referenced from:
      std::rethrow_exception(std::exception_ptr) in exception.o
  "___cxa_uncaught_exception", referenced from:
      std::uncaught_exception() in exception.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I was not sure what to do after that.

So because of these errors, I did not build the libc++.

I am not sure if these issues are connected but I though I would mention it.

**Comment by sandym** [comment]
Look to me like you haven't set the TRIPLE environment variable. I should probably make that setup_llvm.txt into a real script to avoid this.

**Comment by spsaul20** [comment]
I set the TRIPLE environment variable.  I left the terminal active with my attempt to finish the instruction in setup_llvm.txt.  I ran the echo $TRIPLE and it returned -apple-.

I have to run sudo for most of the commands.  I don't think that is an issue, but again I am just mentioning anything that may mean something more to you then it does to me.  I am assuming you have things working on your computer and with your environment.  Maybe there is something about my environment or set up that is different.

**Comment by sandym** [comment]
setup_llvm.txt is just my personal notes on building clang, it comes from http://clang.llvm.org/get_started.html and http://libcxx.llvm.org.

You can see in the buildit script that if TRIPLE is set to -apple- then there is no -soname and no -lrt used. All I can say is double check all, you missed something.

I changed the owner of the llvm and llvm_build folder for an easier workflow:

sudo chown YOURUSER:staff -R /opt/llvm*

otherwise, yeah you might have to use sudo.

As for Xcode 6.1, you might have an issue with the swift code itself, I updated it to swift 1.2. You can install 6.1 and 6.3 side-by-side, like I did. Or don't use the latest version of the example *.swift files. Everything else should work.

**Comment by spsaul20** [comment]
I followed your instructions and I finally have the example app working.

You were right; the TRIPLE environment variable was not getting set (nor the CXX and CC ).  I believe it was a permissions thing.  Once I chown'ed the appropriate directory, I was able to build libc++.

Thanks!

**Comment by sandym** [comment]
Ah, of course! If you export TRIPLE to your environment and then build with sudo (root environment) then the script won't see TRIPLE! Thanks for pointing that, I'll see what I can do to make this easier.
